/**
 * THE GENERATOR — TypeScript is the source, CSS is the artifact.
 *
 * Implements docs/token-contract.md §10, "Direction of generation: TypeScript →
 * CSS". Four reasons, and the second is the one that settles it:
 *
 *   1. The values must exist in TS anyway — `applyTheme` writes themes at
 *      runtime and an editor reads `TOKEN_META`. CSS-canonical would need a CSS
 *      parser in the browser, or a second copy, which is the drift being avoided.
 *   2. A TYPO IN CSS BECOMES A VALID TOKEN. Going CSS → types means the compiler
 *      learns the vocabulary from the file that can contain mistakes, so
 *      `--color-bg-surfcae` would become a legal `ColorToken`. Going TS → CSS, a
 *      typo is a compile error at the definition site.
 *   3. One edit adds a token. Today, adding one to Nanite is four edits in three
 *      files.
 *   4. Charts need real colour strings in JS (§3.6); a CSS-canonical design
 *      cannot serve them without a second export.
 *
 * THE GENERATED CSS IS COMMITTED AND REVIEWABLE, and `scripts/generate.mjs
 * --check` fails when the committed file differs from the generated one. That
 * check runs as a test (`test/generated-css.test.js`), so it is part of the
 * repo's existing CI gate rather than a new step someone has to remember.
 *
 * ── ONE ANSWER TO CW-0124's OPEN CALL: CSS-FIRST OR TS-FIRST FOR VALUES? ──────
 * Neither alone. HYBRID, and here is the "why" the task asked for rather than
 * an assumption:
 *
 *   · The CSS is authoritative AT RUNTIME. A consumer imports one stylesheet and
 *     gets every theme with zero JavaScript — sysop-ui's property, and it is
 *     what makes first paint correct and a server-rendered page themeable. It is
 *     also the only version that works for a consumer with no bundler.
 *   · The TS is authoritative AS A SOURCE. It is the only form that can be
 *     type-checked, that a theme editor can enumerate, and that a chart library
 *     can read as strings.
 *
 * The failure mode of picking one is symmetric and known: CSS-only is what left
 * sysop-ui with no type contract, and TS-only is what makes Nanite need a
 * runtime step before anything is themed. Generating one from the other gets
 * both properties with one source, which is the only reason a hybrid is not just
 * two problems.
 */
import { COLOR_TOKENS, FONT_STACKS, FONT_TOKENS, GENERATED_SHADCN_ALIASES, VALUE_PREFIX } from '../tokens.js'
import {
  RADIUS_ALIASES, RADIUS_SCALE, RADIUS_TOKENS,
  TEXT_SCALE, TEXT_TOKENS, TRACKING_SCALE, TRACKING_TOKENS, remOf,
} from '../scales.js'
import { modesOf } from '../theme.js'
import type { Theme, ThemeMode } from '../theme.js'

const BANNER = `/* GENERATED BY @hollis-labs/design-tokens — DO NOT EDIT BY HAND.
 *
 * Source of truth is the TypeScript in this package's src/. Regenerate with
 * \`npm run generate\` and verify with \`npm run generate:check\`, which the test
 * suite runs so a hand-edit fails CI instead of drifting quietly.
 */`

const v = (name: string) => `--${VALUE_PREFIX}-${name}`

/* ──────────────────────────── the contract layer ─────────────────────────── */

/**
 * `@theme inline` for colours, and the `inline` is load-bearing.
 *
 * Without it Tailwind emits `--color-bg: var(--hl-bg)` into `:root` and resolves
 * it THERE, so a `[data-theme]` on anything below `<html>` changes nothing —
 * descendants inherit an already-resolved value. With it, the utility itself
 * references `var(--hl-bg)` and resolves at the element, so a themed subtree
 * works. sysop-ui discovered this; Nanite gets away without it only because its
 * mode marker sits on the root.
 *
 * Scales go in a PLAIN `@theme` block, because a scale step has no value layer
 * beneath it and consumers benefit from `var(--text-label)` existing.
 */
export function emitContractCss(): string {
  const out: string[] = [BANNER, '']

  out.push('@theme inline {')
  out.push('  /* Fonts — §3.9 */')
  for (const f of FONT_TOKENS) out.push(`  --font-${f}: var(${v(`font-${f}`)});`)
  out.push('')
  out.push(`  /* The colour contract — ${COLOR_TOKENS.length} names. §3. */`)
  out.push('  /* A component names these. It never names the --hl-* layer below them. */')
  for (const t of COLOR_TOKENS) out.push(`  --color-${t}: var(${v(t)});`)
  out.push('')
  out.push(`  /* shadcn compatibility aliases — GENERATED, never authored. §3.7. */`)
  out.push('  /* Vendored shadcn components name these; a component we write does not. */')
  for (const [alias, target] of GENERATED_SHADCN_ALIASES) {
    out.push(`  --color-${alias}: var(${v(target)});`)
  }
  out.push('}')
  out.push('')

  out.push('@theme {')
  out.push('  /* Type scale — §4. EXTENDS Tailwind; does not replace it. */')
  out.push('  /* These four are emitted from TEXT_TOKENS, never hand-written, so that */')
  out.push('  /* closing the scale later is one array edit and a regenerate. */')
  for (const t of TEXT_TOKENS) out.push(`  --text-${t}: ${remOf(TEXT_SCALE[t])}; /* ${TEXT_SCALE[t]}px */`)
  out.push('')
  out.push("  /* Radius — §5. Tailwind's ladder is NOT overridden. One new step, one alias. */")
  for (const t of RADIUS_TOKENS) {
    const aliasOf = (RADIUS_ALIASES as Record<string, string | undefined>)[t]
    const note = aliasOf ? ` /* ${RADIUS_SCALE[t]}px — alias of Tailwind's \`${aliasOf}\` */` : ` /* ${RADIUS_SCALE[t]}px — new step */`
    out.push(`  --radius-${t}: ${remOf(RADIUS_SCALE[t])};${note}`)
  }
  out.push('')
  out.push("  /* Letter-spacing — §6. Above Tailwind's top step (`widest`, 0.1em). */")
  for (const t of TRACKING_TOKENS) out.push(`  --tracking-${t}: ${TRACKING_SCALE[t]}em;`)
  out.push('}')
  out.push('')

  out.push('/* ── Convenience: the contract layer as ordinary custom properties ──────────')
  out.push(' *')
  out.push(' * `@theme inline` deliberately does NOT emit --color-* into :root, so this')
  out.push(' * block exists for hand-written CSS and for consumers with no Tailwind at all.')
  out.push(' * Generated from the same array as the block above, so it cannot drift.')
  out.push(' *')
  out.push(' * Root-scoped, unlike the utilities: these resolve against :root, so a')
  out.push(' * [data-theme] on a SUBTREE changes the utilities and not these.')
  out.push(' */')
  out.push(':root {')
  for (const t of COLOR_TOKENS) out.push(`  --color-${t}: var(${v(t)});`)
  for (const [alias, target] of GENERATED_SHADCN_ALIASES) out.push(`  --color-${alias}: var(${v(target)});`)
  out.push('}')
  out.push('')
  return out.join('\n')
}

/* ────────────────────────────── the value layer ──────────────────────────── */

function declarations(theme: Theme, mode: ThemeMode, indent = '  '): string[] {
  const values = mode === 'light' ? theme.tokens.light : theme.tokens.dark
  if (!values) return []
  return COLOR_TOKENS.map((t) => `${indent}${v(t)}: ${values[t]};`)
}

function fontDeclarations(indent = '  '): string[] {
  return FONT_TOKENS.map((f) => `${indent}${v(`font-${f}`)}: ${FONT_STACKS[f]};`)
}

/**
 * One theme's value layer.
 *
 * Selector model, and it unifies the two that exist today:
 *   · THEME is chosen by `[data-theme="<id>"]` — sysop-ui's mechanism.
 *   · MODE is chosen by `[data-mode="light"]` on the SAME element, with `.light`
 *     accepted as a second spelling because that is what Nanite's `apply.ts`
 *     writes and what its `@custom-variant` keys off.
 *
 * `:root:not([data-theme])` carries the default theme so there is no first-paint
 * flash before any attribute is set — sysop-ui's trick, kept — and the `:not()`
 * is what stops the default's light block outranking another theme's dark block.
 */
export function emitThemeCss(theme: Theme, { asDefault = false } = {}): string {
  const out: string[] = []
  const modes = modesOf(theme)
  out.push(`/* ${theme.name} — ${theme.description ?? ''}`)
  out.push(` * id: ${theme.id}   origin: ${theme.origin ?? 'unknown'}   modes: ${modes.join(' + ')}`)
  if (theme.chartPalette === 'placeholder') {
    out.push(' * chart-1..5 are PLACEHOLDERS, not designed values. See the README.')
  }
  if (modes.length === 1) {
    out.push(' * Dark-only: this palette is an alternate, not a mode. There is no light')
    out.push(' * set to carry and inventing one is a design pass, not a port.')
  }
  out.push(' */')

  if (asDefault) {
    out.push(':root:not([data-theme]) {')
    out.push(...declarations(theme, 'dark'))
    out.push('}')
    if (theme.tokens.light) {
      out.push(':root:not([data-theme])[data-mode="light"],')
      out.push(':root:not([data-theme]).light {')
      out.push(...declarations(theme, 'light'))
      out.push('}')
    }
  }

  out.push(`[data-theme="${theme.id}"] {`)
  out.push(...declarations(theme, 'dark'))
  out.push('}')
  if (theme.tokens.light) {
    out.push(`[data-theme="${theme.id}"][data-mode="light"],`)
    out.push(`[data-theme="${theme.id}"].light {`)
    out.push(...declarations(theme, 'light'))
    out.push('}')
  }
  out.push('')
  return out.join('\n')
}

export function emitThemesCss(themes: readonly Theme[], defaultThemeId: string): string {
  const out: string[] = [BANNER, '']
  out.push('/* The VALUE layer — the only layer permitted to name a colour. */')
  out.push('')
  out.push('/* Fonts sit outside the theme blocks on purpose: they are the same in every')
  out.push(' * built-in theme, and a theme that wants its own overrides one variable.')
  out.push(' * Putting them inside the default theme would drop them the moment a')
  out.push(' * consumer set [data-theme] to anything else. */')
  out.push(':root {')
  out.push(...fontDeclarations())
  out.push('}')
  out.push('')
  for (const theme of themes) {
    out.push(emitThemeCss(theme, { asDefault: theme.id === defaultThemeId }))
  }
  return out.join('\n')
}

/** The one-import bundle. */
export function emitBundleCss(): string {
  return [
    BANNER,
    '',
    '/* Everything: the contract layer and every built-in theme.',
    ' *',
    ' *   @import "tailwindcss";',
    ' *   @import "@hollis-labs/design-tokens/design-tokens.css";',
    ' *',
    ' * Import `tokens.css` alone to bring your own values.',
    ' */',
    '@import "./tokens.css";',
    '@import "./themes.css";',
    '',
  ].join('\n')
}

/** Everything the generator writes, as path → contents. */
export function emitAll(themes: readonly Theme[], defaultThemeId: string): Record<string, string> {
  const files: Record<string, string> = {
    'tokens.css': emitContractCss(),
    'themes.css': emitThemesCss(themes, defaultThemeId),
    'design-tokens.css': emitBundleCss(),
  }
  for (const theme of themes) {
    files[`themes/${theme.id}.css`] = [BANNER, '', emitThemeCss(theme)].join('\n')
  }
  return files
}
